create table USUARIO (
    ID number(8) not null primary key,
    NOMBRE varchar2(100) not null,
    EDAD number(4) not null,
    UBICACION varchar2(100),
    TELEFONO varchar2(8) not null,
    ID_CREDENCIALES number(8) not null
);

create sequence USUSARIO_SEQ increment by 1;

create table EMPRESA (
    ID number(8) not null primary key,
    NOMBRE varchar2(100) not null,
    PAGINA varchar(200),
    TELEFONO varchar2(8) not null,
    ID_CREDENCIALES number(8) not null
);

create sequence EMPRESA_SEQ increment by 1;

create table CREDENCIALES (
    ID number(8) not null primary key,
    NOMBRE_USUARIO varchar2(50) not null,
    CORREO varchar2(100) not null,
    CONTRASENHA varchar2(50) not null
);

create sequence CREDENCIALES_SEQ increment by 1;

create table USUARIO_AMIGO (
    ID number(8) not null primary key,
    ID_USUARIO number(8) not null,
    ID_AMIGO number(8) not null,
    FECHA_AMISTAD date
);

create sequence USUARIO_AMIGO_SEQ increment by 1;

create table NOTICIA (
    ID number(8) not null primary key,
    CONTENIDO varchar2(300) not null,
    FECHA date not null,
    TITULAR varchar2(100) not null,
    FUENTE varchar2(100) not null,
    ID_USUARIO number(8) not null,
    ID_TIPO number(8) not null
);

create sequence NOTICIA_SEQ increment by 1;

CREATE TABLE MENSAJE(
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    CONTENIDO VARCHAR2(200) NOT NULL,
    ID_USUARIO_EMISOR NUMBER(8),
    ID_USUARIO_RECEPTOR NUMBER(8)
);

create sequence MENSAJE_SEQ increment by 1;

CREATE TABLE TIPO_PUBLICACION(
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    TEMA_PUBLICACION VARCHAR2(50) NOT NULL,
    TIPO_PUBLICACION VARCHAR(50) NOT NULL
);

create sequence TIPO_SEQ increment by 1;

CREATE TABLE PUBLICACION(
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    TAMANHO_PUBLICACION VARCHAR2(50),
    CONTENIDO VARCHAR2(200) NOT NULL,
    FECHA DATE NOT NULL,
    RESTRICCION_SOLO_AMIGOS NUMBER(1) NOT NULL,
    ID_USUARIO NUMBER(8),
    ID_TIPO NUMBER(8)
);

create sequence PUBLICACION_SEQ increment by 1;



ALTER TABLE EMPRESA
ADD CONSTRAINT "FK_EMPRESA_TO_CREDENCIALES" 
FOREIGN KEY ("ID_CREDENCIALES")
REFERENCES CREDENCIALES ("ID") ENABLE;

ALTER TABLE USUARIO
ADD CONSTRAINT "FK_USUARIO_TO_CREDENCIALES" 
FOREIGN KEY ("ID_CREDENCIALES")
REFERENCES CREDENCIALES ("ID") ENABLE;

ALTER TABLE USUARIO_AMIGO
ADD CONSTRAINT "FK_AMIGO_TO_USUARIO" 
FOREIGN KEY ("ID_USUARIO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE USUARIO_AMIGO
ADD CONSTRAINT "FK_AMIGO_TO_USUARIO2" 
FOREIGN KEY ("ID_AMIGO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE MENSAJE
ADD CONSTRAINT "FK_MENSAJE_TO_USUARIO" 
FOREIGN KEY ("ID_USUARIO_EMISOR")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE MENSAJE
ADD CONSTRAINT "FK_MENSAJE_TO_USUARIO2" 
FOREIGN KEY ("ID_USUARIO_RECEPTOR")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE NOTICIA
ADD CONSTRAINT "FK_NOTICIA_TO_USUARIO" 
FOREIGN KEY ("ID_USUARIO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE NOTICIA
ADD CONSTRAINT "FK_NOTICIA_TO_TIPO" 
FOREIGN KEY ("ID_TIPO")
REFERENCES TIPO_PUBLICACION ("ID") ENABLE;

ALTER TABLE PUBLICACION
ADD CONSTRAINT "FK_PUBLICACION_TO_USUARIO" 
FOREIGN KEY ("ID_USUARIO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE PUBLICACION
ADD CONSTRAINT "FK_PUBLICACION_TO_TIPO" 
FOREIGN KEY ("ID_TIPO")
REFERENCES TIPO_PUBLICACION ("ID") ENABLE;
