DROP TABLE HASHTAG_PUBLICACION;
DROP TABLE TEMAS_PUBLICACION;
DROP TABLE USUARIO_AMIGO;
DROP TABLE NOTICIA;
DROP TABLE MENSAJE;
DROP TABLE LISTA_TEMAS;
DROP TABLE LISTA_HASHTAG;
DROP TABLE PUBLICACION;
DROP TABLE USUARIO;
DROP TABLE CREDENCIALES;
--this should delete all the tables without messing with the fks

DROP SEQUENCE USUARIO_SEQ;
DROP SEQUENCE CREDENCIALES_SEQ;
DROP SEQUENCE USUARIO_AMIGO_SEQ;
DROP SEQUENCE NOTICIA_SEQ;
DROP SEQUENCE MENSAJE_SEQ;
DROP SEQUENCE LISTA_TEMAS_SEQ;
DROP SEQUENCE TEMAS_PUBLICACION_SEQ;
DROP SEQUENCE LISTA_HASHTAG_SEQ;
DROP SEQUENCE HASHTAG_PUBLICACION_SEQ;
DROP SEQUENCE PUBLICACION_SEQ;


CREATE TABLE USUARIO (
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EDAD NUMBER(4) NOT NULL,
    UBICACION VARCHAR2(100),
    TELEFONO VARCHAR2(8) NOT NULL,
    ID_CREDENCIALES NUMBER(8) NOT NULL
);

CREATE SEQUENCE USUARIO_SEQ INCREMENT BY 1;

CREATE TABLE CREDENCIALES (
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    CONTRASENHA VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE CREDENCIALES_SEQ INCREMENT by 1;

CREATE TABLE USUARIO_AMIGO (
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    ID_USUARIO NUMBER(8) NOT NULL,
    ID_AMIGO NUMBER(8) NOT NULL,
    FECHA_AMISTAD DATE
);

CREATE SEQUENCE USUARIO_AMIGO_SEQ INCREMENT by 1;

CREATE TABLE NOTICIA (
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    TITULAR VARCHAR2(100) NOT NULL,
    FUENTE VARCHAR2(100) NOT NULL,
    ID_PUBLICACION NUMBER(8) NOT NULL
);

CREATE SEQUENCE NOTICIA_SEQ INCREMENT by 1;

CREATE TABLE MENSAJE(
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    CONTENIDO VARCHAR2(200) NOT NULL,
    ID_USUARIO_EMISOR NUMBER(8) NOT NULL,
    ID_USUARIO_RECEPTOR NUMBER(8) NOT NULL
);

CREATE SEQUENCE MENSAJE_SEQ INCREMENT by 1;

CREATE TABLE LISTA_TEMAS (
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    TEMA_PUBLICACION VARCHAR2(50) NOT NULL,
    TIPO_PUBLICACION VARCHAR(50) NOT NULL
);

create SEQUENCE LISTA_TEMAS_SEQ INCREMENT by 1;

CREATE TABLE LISTA_HASHTAG (
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    NOMBRE_HASHTAG VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE LISTA_HASHTAG_SEQ INCREMENT by 1;

CREATE TABLE HASHTAG_PUBLICACION(
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    ID_HASHTAG NUMBER(8) NOT NULL,
    ID_PUBLICACION NUMBER(8) NOT NULL
);

CREATE SEQUENCE HASHTAG_PUBLICACION_SEQ INCREMENT by 1;

CREATE TABLE PUBLICACION(
    ID NUMBER(8) NOT NULL PRIMARY KEY,
    FECHA DATE NOT NULL,
    ID_LISTA_TEMAS NUMBER(8) NOT NULL,
    CONTENIDO VARCHAR2(300),
    ID_USUARIO NUMBER(8)
);

create SEQUENCE PUBLICACION_SEQ INCREMENT by 1;


ALTER TABLE USUARIO
ADD CONSTRAINT "FK_USUARIO_TO_CREDENCIALES" 
FOREIGN KEY ("ID_CREDENCIALES")
REFERENCES CREDENCIALES ("ID") ENABLE;

ALTER TABLE USUARIO_AMIGO
ADD CONSTRAINT "FK_USUARIO_TO_AMIGO" 
FOREIGN KEY ("ID_USUARIO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE USUARIO_AMIGO
ADD CONSTRAINT "FK_USUARIO_TO_AMIGO2" 
FOREIGN KEY ("ID_AMIGO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE NOTICIA
ADD CONSTRAINT "FK_NOTICIA_TO_PUBLICACION" 
FOREIGN KEY ("ID_PUBLICACION")
REFERENCES PUBLICACION ("ID") ENABLE;

ALTER TABLE MENSAJE
ADD CONSTRAINT "FK_MENSAJE_TO_EMISOR" 
FOREIGN KEY ("ID_USUARIO_EMISOR")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE MENSAJE
ADD CONSTRAINT "FK_MENSAJE_TO_RECEPTOR" 
FOREIGN KEY ("ID_USUARIO_RECEPTOR")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE HASHTAG_PUBLICACION
ADD CONSTRAINT "FK_PUBLICACION_TO_HASHTAG_PUBLICACION" 
FOREIGN KEY ("ID_PUBLICACION")
REFERENCES PUBLICACION ("ID") ENABLE;

ALTER TABLE HASHTAG_PUBLICACION
ADD CONSTRAINT "FK_HASHTAG_TO_HASHTAG_PUBLICACION" 
FOREIGN KEY ("ID_HASHTAG")
REFERENCES LISTA_HASHTAG ("ID") ENABLE;

ALTER TABLE PUBLICACION
ADD CONSTRAINT "FK_PUBLICACION_TO_USUARIO" 
FOREIGN KEY ("ID_USUARIO")
REFERENCES USUARIO ("ID") ENABLE;

ALTER TABLE PUBLICACION
ADD CONSTRAINT "FK_PUBLICACION_TO_TEMAS" 
FOREIGN KEY ("ID_LISTA_TEMAS")
REFERENCES LISTA_TEMAS ("ID") ENABLE;
